sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  # - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
env:
  global:
    - COVERAGE=1
before_install:
  - cpanp x
  - git clone --depth=1 git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - local-lib dzil
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - prove -lr $(test-dirs)<F24><F25>
